/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AgentRelayCloudWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "AppDatabase": {
      "clusterArn": string
      "database": string
      "host": string
      "password": string
      "port": number
      "reader": string
      "secretArn": string
      "type": "sst.aws.Aurora"
      "username": string
    }
    "AuthSessionSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BrokerKeySecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CloudVpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "CredentialEncryptionKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CredentialProxyJwtSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CredentialProxyUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DaytonaApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NangoSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NangoSyncQueue": {
      "type": "sst.aws.Queue"
      "url": string
      "arn": string
    }
    "RelayJwtSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RelayauthApi": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "RelayauthDatabase": {
      "databaseId": string
      "type": "sst.cloudflare.D1"
    }
    "RelayauthInternalSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RelayauthKv": {
      "namespaceId": string
      "type": "sst.cloudflare.Kv"
    }
    "RelaycronApi": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "RelaycronDatabase": {
      "databaseId": string
      "type": "sst.cloudflare.D1"
    }
    "RelayfileApi": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "RelayfileCleanupHandler": {
      "type": "sst.cloudflare.Worker"
    }
    "RelayfileContentBucket": {
      "name": string
      "type": "sst.cloudflare.Bucket"
    }
    "RelayfileDatabase": {
      "databaseId": string
      "type": "sst.cloudflare.D1"
    }
    "RelayfileEnvelopeDlq": {
      "type": "sst.cloudflare.Queue"
    }
    "RelayfileEnvelopeQueue": {
      "type": "sst.cloudflare.Queue"
    }
    "RelayfileInternalHmacSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RelayfileKv": {
      "namespaceId": string
      "type": "sst.cloudflare.Kv"
    }
    "RelayfileWritebackQueue": {
      "type": "sst.cloudflare.Queue"
    }
    "Router": {
      "type": "sst.aws.Router"
      "url": string
    }
    "SageCloudApiToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SandboxStorage": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "WorkflowStorage": {
      "bucketName": string
      "stsRoleArn": string
      "type": "sst.sst.Linkable"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}
