import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { once } from "node:events";
import { existsSync } from "node:fs";
import net from "node:net";
import test from "node:test";

const workerEntry = "packages/persona-compile-worker/src/index.ts";
const wranglerBin = process.env.WRANGLER_BIN || (process.platform === "win32"
  ? "node_modules/.bin/wrangler.cmd"
  : "node_modules/.bin/wrangler");

test("persona compile worker compiles a staged sample agent in workerd", async () => {
  assert.ok(
    existsSync(wranglerBin),
    `wrangler binary not found at ${wranglerBin}; run npm install before smoke tests`,
  );
  const port = await findOpenPort();
  const wrangler = spawn(
    wranglerBin,
    [
      "dev",
      workerEntry,
      "--local",
      "--ip",
      "127.0.0.1",
      "--port",
      String(port),
      "--name",
      "persona-compile-worker-smoke",
      "--compatibility-date",
      "2026-05-14",
      "--compatibility-flag",
      "nodejs_compat",
    ],
    {
      stdio: ["ignore", "pipe", "pipe"],
      detached: process.platform !== "win32",
    },
  );

  let output = "";
  wrangler.stdout.setEncoding("utf8");
  wrangler.stderr.setEncoding("utf8");
  wrangler.stdout.on("data", (chunk) => {
    output += chunk;
  });
  wrangler.stderr.on("data", (chunk) => {
    output += chunk;
  });

  try {
    await waitForReady(() => output.includes(`http://127.0.0.1:${port}`), () => output);
    const response = await fetch(`http://127.0.0.1:${port}/compile`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        personaId: "smoke-agent",
        entryPoint: "agent.ts",
        files: {
          "agent.ts": `
            import { defineAgent } from "@agentworkforce/runtime";
            import { helper } from "./helper";
            import processInfo from "./process-info.cjs";

            export default defineAgent({
              triggers: { github: [{ on: "pull_request.opened" }] },
              handler: async () => ({ ...helper("compiled"), process: processInfo.name })
            });
          `,
          "helper.ts": `
            export function helper(value: string) {
              return { value, ok: true };
            }
          `,
          "process-info.cjs": `
            const process = require("process");
            module.exports = { name: process.release.name };
          `,
        },
      }),
    });

    const payload = await response.json();
    assert.equal(response.status, 200, JSON.stringify(payload));
    assert.equal(typeof payload.runner, "string");
    assert.equal(typeof payload.agent, "string");
    assert.equal(payload.packageJson.name, "@agentworkforce/deployed-smoke-agent");
    assert.equal(payload.packageJson.dependencies["@agentworkforce/runtime"], "*");
    assert.match(payload.runner, /Generated by @agentworkforce\/deploy/);
    assert.match(payload.agent, /__agentworkforceCreateRequire/);
    assert.match(payload.agent, /require\("process"\)/);
    assert.match(payload.agent, /pull_request\.opened/);
    assert.match(payload.agent, /compiled/);

    const badPathResponse = await fetch(`http://127.0.0.1:${port}/compile`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        personaId: "bad-path-agent",
        entryPoint: "../agent.ts",
        agentSource: "export default async function handler() {}",
      }),
    });
    const badPathPayload = await badPathResponse.json();
    assert.equal(badPathResponse.status, 400, JSON.stringify(badPathPayload));
    assert.equal(badPathPayload.code, "bad_request");
    assert.match(badPathPayload.error, /virtual source root/);
  } finally {
    await stopProcess(wrangler);
  }
});

async function findOpenPort() {
  const server = net.createServer();
  server.listen(0, "127.0.0.1");
  await once(server, "listening");
  const address = server.address();
  assert(address && typeof address === "object");
  const port = address.port;
  server.close();
  await once(server, "close");
  return port;
}

async function waitForReady(predicate, readOutput) {
  const deadline = Date.now() + 20_000;
  while (Date.now() < deadline) {
    if (predicate()) return;
    await new Promise((resolve) => setTimeout(resolve, 100));
  }
  throw new Error(`Timed out waiting for wrangler dev to become ready.\n\n${readOutput()}`);
}

async function stopProcess(child) {
  if (child.exitCode !== null || child.signalCode !== null) return;

  if (process.platform === "win32") {
    child.kill("SIGTERM");
  } else if (child.pid) {
    try {
      process.kill(-child.pid, "SIGTERM");
    } catch {
      child.kill("SIGTERM");
    }
  } else {
    child.kill("SIGTERM");
  }

  const exit = once(child, "exit").catch(() => undefined);
  const timeout = new Promise((resolve) => setTimeout(resolve, 2_000, "timeout"));
  if (await Promise.race([exit, timeout]) === "timeout" && child.pid && process.platform !== "win32") {
    try {
      process.kill(-child.pid, "SIGKILL");
    } catch {
      child.kill("SIGKILL");
    }
    await once(child, "exit").catch(() => undefined);
  }
}
