import { workflow } from '@agent-relay/sdk/workflows';
import { ClaudeModels, CodexModels } from '@agent-relay/config';

async function main() {
  const result = await workflow('057-remediate-first-canonical-schema-proof')
    .description('Remediate the first canonical schema proof so it aligns with the approved boundary and actual adapter-emitted shapes.')
    .pattern('supervisor')
    .channel('wf-057-remediate-first-canonical-schema-proof')
    .maxConcurrency(4)
    .timeout(10_800_000)
    .agent('lead-claude', { cli: 'claude', model: ClaudeModels.OPUS, preset: 'analyst', role: 'Defines the exact bounded remediation slice for the first canonical schema proof.', retries: 1 })
    .agent('impl-codex', { cli: 'codex', model: CodexModels.GPT_5_4, role: 'Implements the remediation and reruns the validation loop.', retries: 1 })
    .agent('review-codex', { cli: 'codex', model: CodexModels.GPT_5_4, preset: 'reviewer', role: 'Reviews whether the proof now matches the intended boundary and real shapes.', retries: 1 })
    .step('read-context', { type: 'deterministic', command: ['echo "---FIRST PROOF REVIEW---"','sed -n "1,320p" docs/first-canonical-schema-proof-review-verdict.md || true','echo "" && echo "---FIRST PROOF PLAN---"','sed -n "1,280p" docs/first-canonical-schema-proof-plan.md || true','echo "" && echo "---OWNERSHIP REVIEW---"','sed -n "1,240p" docs/canonical-file-schema-ownership-review-verdict.md || true'].join(' && '), captureOutput: true, failOnError: true })
    .step('define-boundary', { agent: 'lead-claude', dependsOn: ['read-context'], task: `Define the exact remediation slice for the first canonical schema proof.\n\n{{steps.read-context.output}}\n\nRequirements:\n1. align the proof with the approved first-proof boundary\n2. validate against actual adapter fixture shapes\n3. keep the slice bounded and mergeable\n4. define exact files/tests/gates\n\nWrite:\n- docs/first-canonical-schema-proof-remediation-boundary.md\n- docs/first-canonical-schema-proof-remediation-checklist.md\n- docs/first-canonical-schema-proof-remediation-plan.md\n\nEnd with RELAYFILE_FIRST_CANONICAL_SCHEMA_REMEDIATION_BOUNDARY_READY.`, verification: { type: 'file_exists', value: 'docs/first-canonical-schema-proof-remediation-boundary.md' } })
    .step('implement-remediation', { agent: 'impl-codex', dependsOn: ['define-boundary'], task: `Implement the first canonical schema proof remediation.\n\nRead:\n- docs/first-canonical-schema-proof-remediation-boundary.md\n- docs/first-canonical-schema-proof-remediation-checklist.md\n- docs/first-canonical-schema-proof-remediation-plan.md\n\nRequirements:\n1. make the proof match the approved boundary\n2. validate against actual adapter-emitted shapes\n3. add deterministic conformance checks\n4. use the 80-to-100 discipline\n\nEnd with RELAYFILE_FIRST_CANONICAL_SCHEMA_REMEDIATION_READY.`, verification: { type: 'exit_code' } })
    .step('validate-remediation', { type: 'deterministic', dependsOn: ['implement-remediation'], command: ['npm test 2>&1 || true','npm run build 2>&1 || true'].join(' && '), captureOutput: true, failOnError: false })
    .step('review-remediation', { agent: 'review-codex', dependsOn: ['validate-remediation'], task: `Review the remediation of the first canonical schema proof.\n\nRead:\n- docs/first-canonical-schema-proof-remediation-boundary.md\n- docs/first-canonical-schema-proof-remediation-checklist.md\n- docs/first-canonical-schema-proof-remediation-plan.md\n- changed files\n- validation output:\n{{steps.validate-remediation.output}}\n\nWrite:\n- docs/first-canonical-schema-proof-remediation-review-verdict.md\n\nAssess:\n1. does the proof now align with the intended boundary?\n2. is it validated against real emitted shapes?\n3. is it ready to be treated as the real first canonical schema proof?\n\nEnd with RELAYFILE_FIRST_CANONICAL_SCHEMA_REMEDIATION_REVIEW_COMPLETE.`, verification: { type: 'file_exists', value: 'docs/first-canonical-schema-proof-remediation-review-verdict.md' } })
    .step('verify-artifacts', { type: 'deterministic', dependsOn: ['review-remediation'], command: ['test -f docs/first-canonical-schema-proof-remediation-boundary.md','test -f docs/first-canonical-schema-proof-remediation-checklist.md','test -f docs/first-canonical-schema-proof-remediation-plan.md','test -f docs/first-canonical-schema-proof-remediation-review-verdict.md','grep -q "RELAYFILE_FIRST_CANONICAL_SCHEMA_REMEDIATION_REVIEW_COMPLETE" docs/first-canonical-schema-proof-remediation-review-verdict.md','echo "RELAYFILE_FIRST_CANONICAL_SCHEMA_REMEDIATION_VERIFIED"'].join(' && '), captureOutput: true, failOnError: true })
    .run({ cwd: process.cwd() });
  console.log(result.status);
}
main().catch((error) => { console.error(error); process.exit(1); });
