/**
 * relayfile's CLI surface, mounted by the `agent-relay` CLI as
 * `agent-relay file`.
 *
 * The surface does not reimplement any relayfile command. `commands` is a
 * checked-in snapshot of the Go binary's own command table (emitted by
 * `relayfile __command-spec --json`, regenerated by `npm run gen:command-spec`)
 * and `run` spawns that same binary, so `agent-relay file <cmd>` and
 * `relayfile <cmd>` are the same code path.
 *
 * Structurally typed against `@agent-relay/cli-surface` (a devDependency):
 * this package gains no runtime dependency on relay.
 */

import { spawn } from "node:child_process"
import { readFileSync } from "node:fs"
import os from "node:os"
import path from "node:path"
import { fileURLToPath } from "node:url"

import { RELAYFILE_VERSION } from "../package-version.js"
import {
  announceSetupIntent,
  prepareCloudSession,
  type EnsureCloudSession
} from "./cloud-preflight.js"
import {
  GO_TOOLCHAIN_MISSING_MESSAGE,
  resolveRelayfileBinary,
  type ResolveRelayfileBinaryOptions
} from "./resolve-binary.js"

/** Contract revision implemented here; mirrors `@agent-relay/cli-surface`. */
export const RELAY_CLI_CONTRACT_VERSION = 1

/** Exit code for an argv the surface cannot route. */
export const RELAY_CLI_EXIT_UNKNOWN_COMMAND = 2

export interface RelayCliIo {
  stdout(chunk: string): void
  stderr(chunk: string): void
}

export interface RelayCliArgSpec {
  name: string
  description: string
  required: boolean
  variadic?: boolean
}

export interface RelayCliOptionSpec {
  flags: string
  description: string
  defaultValue?: string | boolean | number
}

export interface RelayCliCommandSpec {
  name: string
  description: string
  aliases?: readonly string[]
  args?: readonly RelayCliArgSpec[]
  options?: readonly RelayCliOptionSpec[]
  subcommands?: readonly RelayCliCommandSpec[]
  deprecated?: { replacement: string; since?: string }
  hidden?: boolean
}

export interface RelayCliSurface {
  id: string
  version: string
  contract: 1
  commands: readonly RelayCliCommandSpec[]
  run(argv: readonly string[], io: RelayCliIo): Promise<number>
}

export interface CreateRelayCliSurfaceOptions {
  /** Binary lookup overrides; forwarded to `resolveRelayfileBinary`. */
  resolve?: ResolveRelayfileBinaryOptions
  /** Environment for the child process and the Cloud preflight. */
  env?: NodeJS.ProcessEnv
  /** Working directory for the child process. */
  cwd?: string
  /**
   * Skip the Cloud sign-in preflight. Only for tests: skipping it makes
   * `agent-relay file setup` behave differently from `relayfile setup`.
   */
  skipCloudPreflight?: boolean
  /** Injected Cloud SDK entry point, for tests. */
  ensureCloudSession?: EnsureCloudSession
}

/**
 * Path of the checked-in command-tree snapshot.
 *
 * Lives next to the compiled module so the published package carries it.
 */
export const COMMAND_SPEC_PATH = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "command-spec.json"
)

let cachedCommands: readonly RelayCliCommandSpec[] | undefined

/**
 * Read the snapshot of the Go binary's command tree.
 *
 * Read from disk rather than imported so the module needs no JSON import
 * attributes and stays loadable from both ESM and a CJS `import()`.
 *
 * @returns The command tree the relayfile binary dispatches.
 */
export function relayfileCommands(): readonly RelayCliCommandSpec[] {
  if (!cachedCommands) {
    cachedCommands = JSON.parse(
      readFileSync(COMMAND_SPEC_PATH, "utf8")
    ) as readonly RelayCliCommandSpec[]
  }
  return cachedCommands
}

/**
 * Every name and alias the relayfile binary routes at the top level.
 *
 * Includes `help` and `__command-spec`, which the binary routes but keeps out
 * of its published surface (the host renders help itself, and
 * `__command-spec` is the introspection hook that produces the snapshot).
 *
 * @returns The routable top-level tokens.
 */
export function routableTopLevelNames(): readonly string[] {
  const names = new Set<string>(["help", "__command-spec"])
  for (const command of relayfileCommands()) {
    names.add(command.name)
    for (const alias of command.aliases ?? []) {
      names.add(alias)
    }
  }
  return [...names]
}

function isFlag(token: string): boolean {
  return token.startsWith("-")
}

/**
 * Exit code convention for a child killed by a signal: 128 + signal number, so
 * callers can tell user cancellation (130 for SIGINT) from a generic failure.
 *
 * @returns The exit code to report for `signal`.
 */
function exitCodeForSignal(signal: NodeJS.Signals): number {
  const signum = (os.constants.signals as Record<string, number | undefined>)[signal]
  return typeof signum === "number" ? 128 + signum : 1
}

/**
 * Create relayfile's mountable CLI surface.
 *
 * @param options - Optional overrides for binary lookup, env, and cwd.
 * @returns A surface satisfying `@agent-relay/cli-surface`'s `RelayCliSurface`.
 */
export function createRelayCliSurface(
  options: CreateRelayCliSurfaceOptions = {}
): RelayCliSurface {
  const commands = relayfileCommands()

  return {
    id: "relayfile",
    version: RELAYFILE_VERSION,
    contract: RELAY_CLI_CONTRACT_VERSION,
    commands,

    async run(argv: readonly string[], io: RelayCliIo): Promise<number> {
      const args = [...argv]
      const env = options.env ?? process.env

      const first = args[0]
      if (first !== undefined && !isFlag(first) && !routableTopLevelNames().includes(first)) {
        io.stderr(`unknown command "${first}"\n`)
        io.stderr(
          `run \`agent-relay file --help\` for the relayfile command tree\n`
        )
        return RELAY_CLI_EXIT_UNKNOWN_COMMAND
      }

      if (!options.skipCloudPreflight) {
        // Agent Relay's Cloud SDK owns interactive login, token refresh,
        // locking, and the canonical session store; the native runtime reads
        // that same store directly. Running this here keeps
        // `agent-relay file setup` identical to `relayfile setup`.
        announceSetupIntent(args, env, (line) => io.stdout(`${line}\n`))
        await prepareCloudSession(args, {
          env,
          writeLine: (line) => io.stdout(`${line}\n`),
          ensureCloudSession: options.ensureCloudSession
        })
      }

      const resolution = resolveRelayfileBinary(options.resolve)
      const command = resolution.command
      const childArgs = [...resolution.args, ...args]
      const cwd = resolution.kind === "go-run" ? resolution.cwd : options.cwd

      return await new Promise<number>((resolve, reject) => {
        // stdin is inherited so interactive prompts (setup, login, delete
        // confirmations) still work; stdout/stderr are piped into `io` because
        // the contract forbids writing to the host's streams directly. No
        // signal handlers are installed: the host owns them.
        const child = spawn(command, childArgs, {
          cwd,
          env,
          stdio: ["inherit", "pipe", "pipe"]
        })

        child.stdout?.setEncoding("utf8")
        child.stderr?.setEncoding("utf8")
        child.stdout?.on("data", (chunk: string) => io.stdout(chunk))
        child.stderr?.on("data", (chunk: string) => io.stderr(chunk))

        child.on("error", (error: NodeJS.ErrnoException) => {
          if (error.code === "ENOENT" && resolution.kind === "go-run") {
            io.stderr(`${GO_TOOLCHAIN_MISSING_MESSAGE}\n`)
            resolve(1)
            return
          }
          reject(error)
        })

        child.on("close", (code, signal) => {
          if (typeof code === "number") {
            resolve(code)
            return
          }
          if (signal) {
            resolve(exitCodeForSignal(signal))
            return
          }
          resolve(1)
        })
      })
    }
  }
}

export {
  RelayfileBinaryNotFoundError,
  resolveRelayfileBinary,
  findSourceCheckoutRoot,
  genericBinaryName,
  platformBinaryName,
  GO_TOOLCHAIN_MISSING_MESSAGE,
  type RelayfileBinaryResolution,
  type ResolveRelayfileBinaryOptions
} from "./resolve-binary.js"

export {
  announceSetupIntent,
  hasValidSetupArguments,
  parseGoDurationMilliseconds,
  parseSetupArguments,
  prepareCloudSession,
  shouldPrepareCloudSession,
  loadCloudSessionSDK,
  DEFAULT_CLOUD_API_URL,
  SETUP_INTENT,
  SETUP_INTENT_PRINTED_ENV,
  type CloudPreflightOptions,
  type EnsureCloudSession
} from "./cloud-preflight.js"
